### ISSUE TITLE
Support `Web`

### ISSUE THREAD

**Issue by gedw99** [woodemi/quick_notify#2]
Please try web.

it works for me.

worth integrating into yours

**Comment by Sunbreak** [comment]
I'm not sure whether to support Web or not. As far as I concern, Web could behave quite differently than other platforms.

Checkout those:
- Web Bluetooth: https://github.com/woodemi/notepad_core
- Web Camera: https://github.com/woodemi/quick-scan-flutter

**Comment by tneotia** [comment]
Web would be very easy to accomplish with the universal_html package and the notifications API. Like this:

html.Notification("title");

No other code necessary.

**Comment by mbfakourii** [comment]
@Sunbreak Please Support

**Comment by Sunbreak** [comment]
> @Sunbreak Please Support

PRs are welcome

**Comment by mbfakourii** [comment]
https://github.com/woodemi/quick_notify/pull/12
