### ISSUE TITLE
Error Invalid notification (no valid small icon)

### ISSUE THREAD

**Issue by klausszilvas** [woodemi/quick_notify#20]
Hello,
when i try to send an Quick notify i got this error:
"java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=quick_notify shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE)"
minSDK:21
targetSDK:30

Any help for this?

**Comment by Sunbreak** [comment]
Could you post your `flutter doctor -v`?

**Comment by EmreSURK** [comment]
Same. 
I believe you do not need flutter doctor.

**Comment by Sunbreak** [comment]
`quick_notify` needs a small icon: https://github.com/woodemi/quick_notify/blob/3c43485efc59e40011152a55d068120f41b359e0/android/src/main/kotlin/com/example/quick_notify/QuickNotifyPlugin.kt#L65-L69

`quick_notify_example` provides a small icon with the exactly name `ic_quick_notify`: https://github.com/woodemi/quick_notify/blob/master/example/android/app/src/main/res/drawable/ic_quick_notify.png

**Comment by klausszilvas** [comment]
Thank you,
sorry for the late response. I saw this in the code and yes, it runs when 1 set exactly "ic_quick_notify.png" in drawable. It's al little bit tricky.

**Comment by Sunbreak** [comment]
Maybe you could help add some document with a PR?
