### ISSUE TITLE
NUGET.exe not found when attempting to run on Windows with quick_notify

### ISSUE THREAD

**Issue by HayHay404** [woodemi/quick_notify#9]
For whatever reason, whenever I add this plugin and attempt to run in on Windows, I receive this error:

Unsure what's going on here.

![image](https://user-images.githubusercontent.com/59212093/129500975-290b096b-244f-4355-9f24-b0ce6754ff7b.png)

**Comment by Sunbreak** [comment]
You'd better read
- Discussion: [How to setup `C++/WinRT` for Flutter plugin on Windows](https://github.com/woodemi/quick_notify/discussions/8)
- Issue comment: https://github.com/woodemi/quick_notify/issues/5#issuecomment-888743117

**Comment by HayHay404** [comment]
Got it working, thanks!
